export const initialState = {
  posts: {
    data: [
      {
        id: 1,
        author:'the.admin@example.com',
        created: '2019-01-01',
        updated: '2019-01-01',
        status: 'published',
        title: 'Welcome to our bulletin board!',
        text: 'Email me to register and get an account!',
        photo: 'https://images.pexels.com/photos/128299/pexels-photo-128299.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
        price: null,
        phone: null,
        location: null,
      },
      {
        id: 2,
        author:'user123@example.com',
        created: '2019-01-05',
        updated: '2019-01-07',
        status: 'published',
        title: 'Room for rent',
        text: 'I have a spare room for rent. Low price!',
        photo: null,
        price: null,
        phone: null,
        location: null,
      },
      {
        id: 3,
        author:'johndoe@example.com',
        created: '2020-01-05',
        updated: '2020-01-05',
        status: 'closed',
        title: 'Lorem ipsum',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error molestias omnis officiis illo repellendus consequuntur eligendi accusamus tempore ex maxime voluptatibus dolorum inventore officia eius iusto optio quisquam, odit vel, recusandae.',
        photo: 'https://images.pexels.com/photos/128299/pexels-photo-128299.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
        price: '200',
        phone: '123456789',
        location: null,
      },
      {
        id: 4,
        author:'amandadoe@example.com',
        created: '2020-01-08',
        updated: '2020-01-08',
        status: 'closed',
        title: 'Lorem ipsum',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error molestias omnis officiis illo repellendus consequuntur eligendi accusamus tempore ex maxime voluptatibus dolorum inventore officia eius iusto optio quisquam, odit vel, recusandae, consequatur voluptate ut asperiores beatae quas. Corrupti magni similique alias repellendus unde. Veritatis nostrum esse eius sint fugiat blanditiis.',
        photo: null,
        price: null,
        phone: null,
        location: null,
      },
      {
        id: 5,
        author:'mary.jane@example.com',
        created: '2020-05-08',
        updated: '2020-06-08',
        status: 'closed',
        title: 'Lorem ipsum',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error molestias omnis officiis illo repellendus consequuntur eligendi accusamus tempore ex maxime voluptatibus dolorum inventore officia eius iusto optio quisquam, odit vel.',
        photo: null,
        price: '150',
        phone: null,
        location: 'California, USA',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: {
    id: 1,
    userEmail: 'johndoe@examle.com',
    logged: false,
  },
  admin: {
    id: 1,
    userEmail: 'the.admin@examle.com',
    logged: false,
  },
};
